### PR TITLE
Add and implement affectedBranches configuration in FileNameHook.

### PR DESCRIPTION
**Pull request by lazartsarev**
Add functionality which allows file name hook to be applied only on specific branches. Branches are configured with regex pattern.

### CODE REVIEW

**Comment by christiangalsterer** [comment]
Thanks for the pull request. I will look into it in the next days.

**Comment by christiangalsterer** [comment]
Thanks for the pull request. I will implement the feature also for the File Size Hook and would cut then a new release 2.3.0 soon.

**Comment by christiangalsterer** [comment]
The new release 2.3.0 is available in the Atlassian Marketplace.

**Comment by lazartsarev** [comment]
Awesome!

**Comment by lazartsarev** [comment]
Hey man, I need hook which validates syntax of changed xml files. Are you ok with me implementing it in this repo?

**Pull request merged**
